config/routes.rb
Rails.application.routes.draw do

  # Static Pages
  root 'static_pages#home'
  get '/connect' => 'static_pages#connect'

  # POSTS
  resources :posts
  get '/blog' => 'posts#index'
  get '/blog/:id' => 'posts#show'

  # TAGS
  resources :tags
  
  # PROJECTS
  resources :projects

  # RESUME
  get '/resume' => 'static_pages#resume'


  # ADMIN
  get '/admin' => 'static_pages#admin', :as => :admin
  
  # USERS
  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :users
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :require_login, :only => [:admin]
  
  def home
    @body_class = 'homepage'
    @post = Post.published.first
    @project = Project.published.first
  end

  def connect
    @alt_header = "Connect"
    @alt_header_url = '/connect'
    @body_class = 'connect'
    @available = User.find_by_name('Nick').accepting_projects
  end

  def resume
    @body_class = 'resume'
    render :layout => 'resume'
  end

  def admin
    @user = current_user
    @tags = Tag.all
    render :layout => 'admin'
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin.html.erb
<section class="section section--admin">
  <h1 class="headline">Admin</h1>
  <hr class="rule">
 
  <%= form_for(@user) do |f| %>
  <div class="checkbox float-left alpha">
    <%= f.check_box :accepting_projects %>
    <% if @user.accepting_projects %>
      <%= f.label :accepting_projects, "Available" %>
    <% else %>
      <%= f.label :accepting_projects, "Not Available" %>
    <% end %>
  </div>
  <%= f.button 'Save Changes', class: 'button', "data-icon" => ""  %>
  <% end %>
</section>

<hr class="rule">

<section class="section section--admin">
  <h1>Posts</h1>
  <%= link_to "New Post", new_post_path, class: "button button--small" %>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Title</th>
        <th>Slug</th>
        <th>Status</th>
        <th>Action</th>
        <th>ID</th>
      </tr>
    </thead>
    <tbody>
    <% @user.posts.each do |post| %>
      <tr>
      <td><%= post.created_at.strftime('%m.%d.%Y') %></td>
      <td><%= post.title %></td>
      <td><%= post.slug %></td>
      <td><%= post.published ? 'Published' : 'Private' %></td>
      <td>
        <%= link_to "View", post_path(post) %> / 
        <%= link_to "Edit", edit_post_path(post) %> / 
        <%= link_to "Delete", post_path(post), :method =>  :delete, "data-remove" => 'tr' %>
      </td>
      <td>
        <%= post.id %>
      </td>
    </tr>
  <% end %>
    </tbody>
  </table>
</section>

<hr class="rule">

<section class="section section--admin">

   <h1>Projects</h1>
   <%= link_to "New Project", new_project_path, class: "button button--small" %>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Name</th>
        <th>Slug</th>
        <th>Status</th>
        <th>Action</th>
        <th>ID</th>
      </tr>
    </thead>
    <tbody>
      <% @user.projects.each do |project| %>
        <tr>
          <td><%= project.created_at.strftime('%m.%d.%Y') %></td>
          <td><%= project.name %></td>
          <td><%= project.slug %></td>
          <td><%= project.published ? 'Published' : 'Private' %></td>
          <td>
            <%= link_to "View", project_path(project) %> / 
            <%= link_to "Edit", edit_project_path(project) %> / 
            <%= link_to "Delete", project_path(project), :method =>  :delete, "data-remove" => 'tr' %>
          </td>
          <td>
            <%= project. id %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</section>

<section class="section section--admin">

   <h1>Tags</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Action</th>
        <th>ID</th>
      </tr>
    </thead>
    <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= tag.name %></td>
          <td>
            <%= link_to "View", tag_path(tag) %> / 
            <%= link_to "Edit", edit_tag_path(tag) %> / 
            <%= link_to "Delete", tag_path(tag), :method =>  :delete, "data-remove" => "tr" %>
          </td>
          <td>
            <%= tag.id %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</section>

app/views/static_pages/connect.html.erb
<section class="section">
    <article class="text-body">

        <h1 class="headline">Welcome.</h1>
        <p>Hello and welcome.  My name is Nick and I enjoy building web experiences that are functional, efficient, and classy.  I focus on simplicity and minimalism.  I'm a self-taught developer with a passion for learning new things.</p>

        <p>You can find some of work on the <a href="/projects">projects</a> page and you can read my various internet findings on my <a href="/blog">blog</a>.  Feel free to email me <a href="mailto:<%= NPB::Application.config.email %>">here</a>.  I host some code at <a href="<%= NPB::Application.config.github_link %>">Github</a>.</p>

        <p>This site was built using:

            <ul>
                <li>Ruby on Rails</li>
                <li>Postgresql</li>
                <li>Intuit CSS Framework</li>
                <li>Bourbon Neat</li>
                <li>RequireJS</li>
                <li>Gulp</li>
                <li>Fonts from Hoefler & Frere Jones</li>
            </ul>

        </p>

        <p>Please have a look around and thank you for stopping by!</p>

         <a href="mailto:nick@npbee.me" class="button <% if @available  %>big-success<% else %>big-error<% end %>" data-icon="" data-icon="">Email Me!*</a>
        <p class="footnote">
            <span class="swatch swatch--green">= Available!</span>
            <span class="swatch swatch--red">= Limited availability</span>
        </p>


    </article>
</section>

app/views/static_pages/home.html.erb
<hr class="rule">

<section class="section home" id="home">
    <header>
        <a href="/" class="site-logo giga"><img src='/assets/images/logo.svg' alt='npb logo'></a>
        <p class="tagline" id="tagline"><span class="headline no-wrap--desk">Web design & Development</span></p>
    </header>
</section>

<hr class="rule">

<section class="recent" id="recent">

    <% if @project && @post %>
    <div class="horizontal-list hl--three">

      <a data-icon="" href="<%= "/projects/#{@project.slug}" %>">
            <h2>Latest Project:</h2>
            <p class="italic"><%= @project.name %></p>
        </a><!--

            --><a data-icon="" href="<%= "/blog/#{@post.slug}" %>">
                <h2>Latest Post:</h2>
                <p class="italic"><%= @post.title %></p>
            </a><!--


        <a data-icon="" xhref="#">
            <h2>Latest Experiment:</h2>
            <p class="italic">Coming soon...</p>
        </a>

        --><a data-icon="" href="/connect">
        <h2>Connect</h2>
        <p class="italic">Find me!</p>
        </a>

    </div> <!-- End horizontal list -->
    <% end %>

</section>

app/views/static_pages/resume.html.erb
  <section>
      <h1>Nicholas Ball</h1>
      <ul>
        <li>San Francisco, CA</li>
        <li><a href="mailto:nicholaspball@gmail.com">nicholaspball@gmail.com</a></li>
        <li><a href="tel:209-380-5272">209.380.5272</a></li>
        <li><a href="https://github.com/npbee">Github</a></li>
      </ul>
  </section>

  <section>
    <h2 class="alpha">Background</h2>
    <p>I am a passionate, self-motivated, and captivated developer.  I have a drive for knowledge and aim to hone my craft to the finest degree.</p>
  </section>

  <section>
    <h2 class="alpha">Work Experience</h2>

    <div class="experience">
     <div class="experience__first">
        <h3 class="beta">Self Employed</h3><!--
        --><p class="italic">Freelance Web Developer</p>
      </div>
      <div class="experience__second">
        <p class="milli">2010 - Present</p>
      </div>

      <h4 class="gamma">Description</h4>
      <p>Working as a freelance web developer is where I have learned the bulk of my development knowledge.  Beginning with basic HTML and CSS, I have since advanced to proficiency in SCSS and Javascript as well as beginning aptitude in Ruby, PHP and SQL.  I've built and deployed both client-side and server-side apps.</p>

      <p></p>

      <h4 class="gamma">Highlights</h4>
      <ul>
        <li>Built a simple, but functional custom CMS using the Laravel PHP framework.  Highlights include site authentication/authorization, drag-and-drop image manipulation, and a custom Soundcloud integration. (<a class="italic" href="https://github.com/npbee/luraymusic.com">Link</a>)</li>
        <li>Using Ajax, integrated several API's into a client-side-only app.  API's include:  Tumblr, Instagram, and Bandsintown (<a class="italic" href="https://github.com/npbee/scarey.org">Link</a>)</li>
        <li>Built a custom CMS with the Ruby on Rails framework for use as a personal blog and portfolio.  Advanced functionality includes:  Administration page for manipulating posts and projects, Markdown support for posts with real-time preview, and a rotating carousel for displaying project images (<a class="italic" href="https://github.com/npbee/npb">Link</a>)</li>
      </ul>

    </div>

    <hr class="rule--small">

    <div class="experience">
      <div class="experience__first">
        <h3 class="beta">Say Media, Inc.</h3><!--
        --><p class="italic">Senior Ad Operator</p>
      </div>
      <div class="experience__second">
        <p class="milli">Aug. 2008 - Present</p>
      </div>

      <h4 class="gamma">Description</h4>
      <p>This position required no programming experience, but I was able to incorporate productive programming aspects into the position.  Throughout my time, I evolved the position into one that provided go-to support for our advanced Javascript functionality, simple Javascript modules for daily use, and debugging of partner sites.</p>
      
      <p>Outside of development knowledge, through this position I have attained several years of experience working in a team environment, coaching and mentoring junior teammates, and communicating in a client-facing manner.</p>

      <h4 class="gamma">Highlights</h4>
      <ul>
        <li>Along with a teammate, I developed an internal tool used by the entire company for daily data analysis.</li>
        <li>Provided support and coaching to other team members on Say's more advanced Javascript technology.  </li>
        <li>Constantly improved and documented team practices and daily functions.</li>
      </ul>
    </div>

    <hr class="rule--small">

  </section>

  <section>
    <h2 class="alpha">Working Knowledge</h2>

    <h3 class="beta">Languages & Technologies</h3>
    <ul>
      <li>HTML5</li>
      <li>SCSS / CSS3</li>
      <li>Javascript</li>
      <li>Ruby</li>
      <li>Git</li>
      <li>Basic knowledge of:  PHP, SQL, and NoSQL</li>
    </ul>

    <h3 class="beta">Frameworks & Libraries</h3>
    <ul>
      <li>SASS:  Compass, Susy, Bourbon, Bourbon Neat, InuitCSS</li>
      <li>Javascript:  jQuery, NodeJS, RequireJS, Browserify, AngularJS, Grunt, Gulp, Jasmine, Karma, Mocha, Chai</li>
      <li>Ruby:  Ruby on Rails, Rspec</li>
      <li>PHP:  Laravel</li>
    </ul>
  </section>

  <section>
    <h2 class="alpha">Education</h2>
    <p class="no-margin-bottom">Bachelor of Science, Management Science</p>
    <p class="italic">University of California, San Diego</p>
  </section>

  <footer>
    <h1>Nicholas Ball</h1>
      <ul>
        <li>San Francisco, CA</li>
        <li><a href="mailto:nicholaspball@gmail.com">nicholaspball@gmail.com</a></li>
        <li><a href="tel:209-380-5272">209.380.5272</a></li>
        <li><a href="https://github.com/npbee">Github</a></li>
      </ul>
  </footer>

 