config/routes.rb
Rails.application.routes.draw do

  # Static Pages
  root 'static_pages#home'
  get '/connect' => 'static_pages#connect'

  # POSTS
  resources :posts
  get '/blog' => 'posts#index'
  get '/blog/:id' => 'posts#show'

  # TAGS
  resources :tags
  
  # PROJECTS
  resources :projects

  # RESUME
  get '/resume' => 'static_pages#resume'


  # ADMIN
  get '/admin' => 'static_pages#admin', :as => :admin
  
  # USERS
  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :users
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_admin_nav.html.erb
<div class="nav-container" id="nav-container">
    <nav class="nav" id="nav">
        <div class="breadcrumbs" id="breadcrumb-hook">
            <a class="nav__logo" href="/"><img class="site-logo--small" src="/assets/images/logo.svg" alt="kinmill logo">ADMIN</a>
            <% if @alt_header %>
                <%= link_to @alt_header, @alt_header_url, :class => 'nav-fade' %>
            <% end %>
            <% if @breadcrumb %>
                <a class="nav-fade" id="breadcrumb"><%= @breadcrumb %></a>
            <% end %>
        </div>
        <ul>
          <% if logged_in? %>
              <li class="dropdown">
              <a data-icon=""><%= current_user.name %></a>
                  <ul>
                    <li><%= link_to "Admin", admin_path %></li>
                    <% if @edit_link && @post && current_user.admin %>
                      <li><%= link_to "Edit Post", edit_post_path(@post) %></li>
                    <% end %>
                    <li><%= link_to "Logout", :logout, method: :post %></li>
                  </ul>
              </li>
            <% end %>
        </ul>
    </nav>
</div>

app/views/shared/_errors.html.erb
<div class="flash flash--explanation" data-icon="">
  <strong class="gamma"><%= pluralize(item.errors.count, "error") %> prohibited this post from being saved:</strong>
  <ul>
    <% item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
  <% end %>
  </ul>
</div>

app/views/shared/_footer.html.erb
<div class="footer-container">

    <div class="footer">
        <a class="footer__copyright italic" href="/">&copy; npb, 2014</a>
        <ul>
            <li>
                <a class="work-nav tooltip" href="/projects" data-icon="">
                    <span class="tooltip-tip">Projects</span>
                </a>
            </li>
            <li>
                <a class="blog-nav tooltip" href="/blog" data-icon="">
                    <span class="tooltip-tip">Blog</span>
                </a>
            </li>
            <!--<li>
                <a class="lab-nav tooltip" href="/lab" data-icon="">
                    <span class="tooltip-tip">Lab</span>
                </a>
            </li>-->
            <li>
                <a class="connect-nav tooltip" href="/connect" data-icon="">
                    <span class="tooltip-tip">Connect</span>
                </a>
            </li>
            <li class="">
            <a class="tooltip" href="<%= NPB::Application.config.github_link %>" data-icon="">
                    <span class="tooltip-tip">Github</span>
                </a>
            </li>
            <li class="">
            <a class="tooltip" data-icon="" href="mailto:<%= NPB::Application.config.email %>">
                    <span class="tooltip-tip">Email</span>
                </a>
            </li>
        </ul>
    </div>

</div>

<script src="/assets/js/main-build.js"></script> 

<% if logged_in? %>
  <script src="/assets/js/admin-build.js"></script>
<% end %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46265154-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_head.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js new-visitor">
    <head>
        <meta http-equiv="Content-Type" content ="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, minimum-scale=1.0">

        <title>npb</title>

        <link rel="icon" type="image/png" href="/favicon.ico">

        <link rel="stylesheet" type="text/css" href="//cloud.typography.com/7821852/698262/css/fonts.css" />
        <link rel="stylesheet" href="/assets/css/style.css">
        <script src="/assets/js/libs/modernizr.js"></script>
    </head>

app/views/shared/_mobile_header.html.erb
<div class="mobile-header" id="mobile-header">
    <a href="/"><img src='/assets/images/logo.svg' alt='npb logo' class='site-logo--small'></a>
    <a href="#nav" class="toggle-container" id="toggle-container">
        <span id="menu-toggle" class="menu-toggle"></span>
    </a>
</div>

app/views/shared/_nav.html.erb
<div class="nav-container" id="nav-container">
    <nav class="nav" id="nav">
        <div class="breadcrumbs" id="breadcrumb-hook">
            <a class="nav__logo" href="/"><img class="site-logo--small" src="/assets/images/logo.svg" alt="npb logo"></a>
            <% if @alt_header %>
                <%= link_to @alt_header, @alt_header_url, :class => 'nav-fade' %>

            <% end %>
            <% if item && item.slug %>
              <a class="nav-fade" id="breadcrumb" href="<%= item.slug %>"><%= item.slug %></a>
            <% end %>
        </div>
        <ul>
            <li><a class="work-nav" href="/projects" data-icon="">Projects</a></li>
            <li><a class="blog-nav" href="/blog" data-icon="">Blog</a></li>
            <!-- <li><a class="lab-nav" href="/lab" data-icon="">Lab</a></li> -->
            <li><a class="connect-nav" href="/connect" data-icon="">Connect</a></li>
            <% if logged_in? %>
              <li class="dropdown">
                <a data-icon=""><%= current_user.name %></a>
                  <ul>
                    <li><%= link_to "Admin", admin_path %></li>
                    <% if @edit_link && @post && current_user.admin %>
                      <li><%= link_to "Edit Post", edit_post_path(@post) %></li>
                    <% elsif @edit_link && @project && current_user.admin %>
                      <li><%= link_to "Edit Project", edit_project_path(@project) %></li>
                    <% elsif @edit_link && @tag && current_user.admin %>
                      <li><%= link_to "Edit Tag", edit_tag_path(@tag) %></li>
                    <% end %>
                    <li><%= link_to "Logout", :logout, method: :post %></li>
                  </ul>
              </li>
            <% end %>
        </ul>
    </nav>
</div>