config/routes.rb
Rails.application.routes.draw do

  # Static Pages
  root 'static_pages#home'
  get '/connect' => 'static_pages#connect'

  # POSTS
  resources :posts
  get '/blog' => 'posts#index'
  get '/blog/:id' => 'posts#show'

  # TAGS
  resources :tags
  
  # PROJECTS
  resources :projects

  # RESUME
  get '/resume' => 'static_pages#resume'


  # ADMIN
  get '/admin' => 'static_pages#admin', :as => :admin
  
  # USERS
  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :users
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :presence => true 
  validates :role, :presence => true 
  validates :url, :presence => true 
  validates :body, :presence => true 
  validates :logo, :presence => true 
  validates :thumbnail, :presence => true 
  validates :slug, :uniqueness => true
  validates_format_of :thumbnail,
                      :small_screen,
                      :medium_screen,
                      :large_screen,
                      :with => /(.)+\.(jpg|svg|png|jpeg)\z/,
                      message: "path should end in .jpg, .svg, .png, or .jpeg."

  belongs_to :user
  has_many :tag_relationships, 
            -> { where reference_type: 'project' },
            :foreign_key => "reference_id"
  
  has_many :tags, :through => :tag_relationships 
  
  default_scope { order('created_at DESC') }
  scope :published, -> { where(published: true) }

  def self.find(input)
    input.to_i == 0 ? find_by_slug(input) : super
  end
 
  def tag_list
    self.tags.map { |tag| tag.name }.join(', ')
  end

  def tag_list=(new_value)
    tag_names = new_value.split(/,\s+/)
    self.tags = tag_names.map { |name| Tag.where('name = ?', name.downcase).first or Tag.create(:name => name.downcase) }
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :require_login, only: [:new, :edit, :create, :update, :destroy]
  layout "admin", only: [:new, :create, :edit]
  
  # GET /projects
  def index
    @projects = Project.published.all
  end

  # GET /projects/1
  def show
    @edit_link = true
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = current_user.projects.build(project_params)

    if !current_user.admin
      redirect_to admin_path, notice: "You cannot create projects as a guest."
    elsif current_user.admin && @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if !current_user.admin
      redirect_to admin_path, notice: "You cannot update posts as a guest."
    elsif current_user.admin && @project.update(project_params)
      redirect_to admin_path, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
      @project_images = [@project.small_screen, @project.medium_screen, @project.large_screen]
      check_access(@project)
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:name, 
                                      :role, 
                                      :url, 
                                      :date_completed, 
                                      :body, 
                                      :logo, 
                                      :thumbnail, 
                                      :small_screen, 
                                      :medium_screen, 
                                      :large_screen, 
                                      :tag_list,
                                      :slug,
                                      :published)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <%= render 'shared/errors', item: @project %>
  <% end %>

  <ul class="form-fields">

  <li>
  <%= f.label :name, class: "beta" %>
  <%= f.text_field :name %>
  </li>

  <li>
  <%= f.label :role , class: "beta"%>
  <%= f.text_field :role %>
  </li>

  <li>
  <%= f.label :url , class: "beta"%>
  <%= f.text_field :url %>
  </li>

  <li>
  <%= f.label :date_completed, class: "beta"%>
  <%= date_field("project", "date_completed") %>
  </li>

  <li>
    <div class="editor">
      <div class="editor__raw">
        <%= f.label :body, "Markdown", class: "beta" %>
        <%= f.text_area :body, id: 'editor__raw__input', "oninput" => "this.editor.update()" %>
      </div>
      <div class="editor__preview">
        <h2>Preview</h2>
        <div id="editor__preview__text" class="editor__preview__text"></div>
      </div>
    </div>
  </li>


  <li>
  <%= f.label :logo, class: "beta" %>
  <%= f.text_field :logo %>
  </li>

  <li>
  <%= f.label :thumbnail, class: "beta" %>
  <%= f.text_field :thumbnail %>
  </li>

  <li>
  <%= f.label :small_screen, class: "beta" %>
  <%= f.text_field :small_screen %>
  </li>

  <li>
  <%= f.label :medium_screen, class: "beta" %>
  <%= f.text_field :medium_screen %>
  </li>

  <li>
  <%= f.label :large_screen, class: "beta" %>
  <%= f.text_field :large_screen %>
  </li>

  <li>
  <%= f.label :tag_list, class: "beta" %>
  <%= f.text_field :tag_list %>
  </li>

  <li>
  <%= f.label :slug, class: "beta" %>
  <%= f.text_field :slug %>
  </li>

  <li class="checkbox">
    <%= f.check_box :published %>
    <%= f.label :published, @project.published ? "Published" : "Private", class: "beta" %>
  </li>

  <li>
  <%= f.button nil, class: "button", id: "submit", "data-icon" => "" %>
  </li>
</ul>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<section class="section">
  <%= render 'form' %>

  <%= link_to 'Show', @project %> |
  <%= link_to 'Back', projects_path %>
</section>

app/views/projects/index.html.erb
<div class="work-thumbs" id="work-thumbs">

  <% @projects.each do |project| %>
    <a data-target="<%= "projects/#{project.slug}" %>" title="<%= project.name %>" href="<%= "/projects/#{project.slug}" %>">
      <img class="work-thumb__icon" src="<%= "/assets/images/#{project.thumbnail}" %>" alt="<%= "#{project.name} thumb"%>">
      <div class="work-thumb__caption" d data-icon="">
        <h2 class="gamma"><%= "#{project.name} (#{project.date_completed.strftime('%Y')})" %></h2>
        <p><%= project.role %></p>
      </div>
    </a>
  <% end %>
</div>

<section class="section">
    <article class="work-item" id="work-item"></article>
</section>

app/views/projects/new.html.erb
<h1>New project</h1>

<section class="section">
  <%= render 'form' %>
  <%= link_to 'Back', projects_path %>
</section>

app/views/projects/show.html.erb
<article id="<%= @project.name %>" class="work-item" title="<%= @project.name%>">

  <h1 class="headline"><%= @project.name %></h1>

  <div class="horizontal-list">
    <div>
      <h2>Role:</h2>
      <p><%= @project.role %></p>
    </div><!--

                    --><div>
      <h2>URL:</h2>
      <p><a href="<%= @project.url %>" target="_blank"><%= @project.url %></a></p>
    </div><!--

                    --><div>
      <h2>Completed:</h2>
      <p><%= @project.date_completed.strftime('%B %d, %Y') %></p>
    </div><!--

                    --><div>
      <h2>Tags:</h2>
      <p>
      <% @project.tags.each do |tag| %>
          <%= link_to tag.name, tag_path(tag.name), class: "pill" %>
        <% end %>
      </p>
    </div>
  </div>

  <div class="carousel-container" id="carousel-container">
    <div class="carousel" id="carousel">

      <span data-picture data-alt="<%= "#{@project.name} small"%>" class="carousel__img carousel__img--mobile">
        <span data-src="<%= "/assets/images/#{@project.small_screen}" %>"></span>
        <span data-src="<%= "/assets/images/#{@project.small_screen}" %>" data-media="(min-width: 940px)"></span>
        <noscript>
          <img src="<%= "/assets/images/#{@project.small_screen}" %>" alt="<%= "#{@project.name} small" %>">
        </noscript>
      </span>

       <span data-picture data-alt="<%= "#{@project.name} medium"%>" class="carousel__img carousel__img--tablet">
        <span data-src="<%= "/assets/images/#{@project.medium_screen}" %>"></span>
        <span data-src="<%= "/assets/images/#{@project.medium_screen}" %>" data-media="(min-width: 940px)"></span>
        <noscript>
          <img src="<%= "/assets/images/#{@project.medium_screen}" %>" alt="<%= "#{@project.name} medium" %>">
        </noscript>
      </span>

      <span data-picture data-alt="<%= "#{@project.name} large"%>" class="carousel__img carousel__img--desk">
        <span data-src="<%= "/assets/images/#{@project.large_screen}" %>"></span>
        <span data-src="<%= "/assets/images/#{@project.large_screen}" %>" data-media="(min-width: 940px)"></span>
        <noscript>
          <img src="<%= "/assets/images/#{@project.large_screen}" %>" alt="<%= "#{@project.name} large" %>">
        </noscript>
      </span>

    </div>
  </div>

  <div class="carousel__controls">
    <a class="button" id="carousel__control" data-icon="">Rotate</a>
  </div>

  <hr class="rule">

  <div class="text-body">
    <%= markdown @project.body %>
  </div>

  <a class="project-logo" href="<%= @project.url %>">
    <img src="/assets/images<%= @project.logo %>" alt="<%= "#{@project.name} logo" %>">
  </a>


  <div class="horizontal-list">
    <div>
      <h2>Role:</h2>
      <p><%= @project.role %></p>
    </div><!--

                    --><div>
      <h2>URL:</h2>
      <p><a href="<%= @project.url %>" target="_blank"><%= @project.url %></a></p>
    </div><!--

                    --><div>
      <h2>Completed:</h2>
      <p><%= @project.date_completed.strftime('%B %d, %Y') %></p>
    </div><!--

                    --><div>
      <h2>Tags:</h2>
      <p> 
        <% @project.tags.each do |tag| %>
          <%= link_to tag.name, tag_path(tag.name) %>
        <% end %>
      </p>
    </div>
  </div>

</article>

<% if logged_in? && current_user.admin %>
  <%= link_to 'Edit', edit_project_path(@project) %>
<% end %>